site_name: My Docs

theme:
    name: material
    language: en

extra:
  alternate:
    - name: English
      link: en/
      lang: en

    - name: Chinese
      link: zh/
      lang: zh
    
plugins:
    - mkdocs_material_multilang_toc
